# configuration file for dotnet-releaser
# Disable default packs - It will only publish NuGet and the Changelog
[msbuild]
project = "XenoAtom.Interop.libgit2.sln"
[changelog]
publish = false # Disable changelog for now
[github]
user = "XenoAtom"
repo = "XenoAtom.Interop"
version_prefix = "libgit2/"