name: ci_publish_LIBNAME

on:
  push:
    tags:
      - "LIBNAME/*"
    paths:
    - 'src/*.props'
    - 'src/LIBNAME/**'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      dotnet-releaser-path: 'src/LIBNAME/dotnet-releaser.toml'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
