<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)../../TestsShared.props" />

  <ItemGroup>
    <PackageReference Include="elskom.zlib.redist.win" />
    <PackageReference Include="elskom.zlib.redist.linux" />
    <PackageReference Include="elskom.zlib.redist.osx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XenoAtom.Interop.zlib\XenoAtom.Interop.zlib.csproj" />
  </ItemGroup>

</Project>
