<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)../../TestsShared.props" />

  <ItemGroup>
    <PackageReference Include="Silk.NET.Shaderc.Native" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XenoAtom.Interop.libshaderc\XenoAtom.Interop.libshaderc.csproj" />
  </ItemGroup>

</Project>