// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
using System.Collections.Generic;

namespace XenoAtom.Interop.CodeGen.musl;

internal partial class MuslGenerator
{
    private static readonly Dictionary<string, string[]> MapLibCFunctionToArgumentNames = new()
    {
        { "_Exit", [ "status" ] },
        { "__fbufsize", [ "stream" ] },
        { "__flbf", [ "stream" ] },
        { "__fpending", [ "stream" ] },
        { "__fpurge", [ "stream" ] },
        { "__freadable", [ "stream" ] },
        { "__freading", [ "stream" ] },
        { "__fsetlocking", [ "stream", "type" ] },
        { "__fwritable", [ "stream" ] },
        { "__fwriting", [ "stream" ] },
        { "__setfpucw", [ "control_word" ] },
        { "_exit", [ "status" ] },
        { "_sysctl", [ "args" ] },
        { "a64l", [ "str64" ] },
        { "abs", [ "j" ] },
        { "accept", [ "sockfd", "addr", "addrlen" ] },
        { "accept4", [ "sockfd", "addr", "addrlen", "flags" ] },
        { "access", [ "pathname", "mode" ] },
        { "acct", [ "filename" ] },
        { "acos", [ "x" ] },
        { "acosf", [ "x" ] },
        { "acosh", [ "x" ] },
        { "acoshf", [ "x" ] },
        { "acoshl", [ "x" ] },
        { "acosl", [ "x" ] },
        { "add_key", [ "type", "description", "payload", "plen", "keyring" ] },
        { "addmntent", [ "stream", "mnt" ] },
        { "addseverity", [ "severity", "s" ] },
        { "adjtime", [ "delta", "olddelta" ] },
        { "adjtimex", [ "buf" ] },
        { "aio_cancel", [ "fd", "aiocbp" ] },
        { "aio_error", [ "aiocbp" ] },
        { "aio_fsync", [ "op", "aiocbp" ] },
        { "aio_init", [ "init" ] },
        { "aio_read", [ "aiocbp" ] },
        { "aio_return", [ "aiocbp" ] },
        { "aio_suspend", [ "aiocb_list", "timeout" ] },
        { "aio_write", [ "aiocbp" ] },
        { "alarm", [ "seconds" ] },
        { "aligned_alloc", [ "alignment", "size" ] },
        { "alloca", [ "size" ] },
        { "alphasort", [ "a", "b" ] },
        { "arc4random_buf", [ "buf", "n" ] },
        { "arc4random_uniform", [ "upper_bound" ] },
        { "argz_add", [ "argz", "argz_len", "str" ] },
        { "argz_add_sep", [ "argz", "argz_len", "str", "delim" ] },
        { "argz_append", [ "argz", "argz_len", "buf", "buf_len" ] },
        { "argz_count", [ "argz", "argz_len" ] },
        { "argz_create", [ "argv", "argz_len" ] },
        { "argz_create_sep", [ "str", "sep", "argz", "argz_len" ] },
        { "argz_delete", [ "argz", "argz_len", "entry" ] },
        { "argz_extract", [ "argz", "argz_len", "argv" ] },
        { "argz_insert", [ "argz", "argz_len", "before", "entry" ] },
        { "argz_next", [ "argz", "argz_len", "entry" ] },
        { "argz_replace", [ "argz", "argz_len", "str", "with", "replace_count" ] },
        { "argz_stringify", [ "argz", "len", "sep" ] },
        { "asctime", [ "tm" ] },
        { "asctime_r", [ "tm", "buf" ] },
        { "asin", [ "x" ] },
        { "asinf", [ "x" ] },
        { "asinh", [ "x" ] },
        { "asinhf", [ "x" ] },
        { "asinhl", [ "x" ] },
        { "asinl", [ "x" ] },
        { "asprintf", [ "strp", "fmt" ] },
        { "assert", [ "expression" ] },
        { "assert_perror", [ "errnum" ] },
        { "atan", [ "x" ] },
        { "atan2", [ "y", "x" ] },
        { "atan2f", [ "y", "x" ] },
        { "atan2l", [ "y", "x" ] },
        { "atanf", [ "x" ] },
        { "atanh", [ "x" ] },
        { "atanhf", [ "x" ] },
        { "atanhl", [ "x" ] },
        { "atanl", [ "x" ] },
        { "atexit", [ "function" ] },
        { "atof", [ "nptr" ] },
        { "atoi", [ "nptr" ] },
        { "atol", [ "nptr" ] },
        { "atoll", [ "nptr" ] },
        { "backtrace", [ "buffer", "size" ] },
        { "backtrace_symbols", [ "buffer", "size" ] },
        { "backtrace_symbols_fd", [ "buffer", "size", "fd" ] },
        { "basename", [ "path" ] },
        { "bcmp", [ "s1", "s2", "n" ] },
        { "bcopy", [ "src", "dest", "n" ] },
        { "bdflush", [ "func", "address" ] },
        { "be16toh", [ "big_endian_16bits" ] },
        { "be32toh", [ "big_endian_32bits" ] },
        { "be64toh", [ "big_endian_64bits" ] },
        { "bind", [ "sockfd", "addr", "addrlen" ] },
        { "bindresvport", [ "sockfd", "sin" ] },
        { "bpf", [ "cmd", "attr", "size" ] },
        { "brk", [ "addr" ] },
        { "bsd_signal", [ "signum", "handler" ] },
        { "bsearch", [ "key", "base", "nmemb", "nmemb", "size", "compar", "size", "size" ] },
        { "bswap_16", [ "x" ] },
        { "bswap_32", [ "x" ] },
        { "bswap_64", [ "x" ] },
        { "btowc", [ "c" ] },
        { "bzero", [ "s", "n" ] },
        { "cabs", [ "z" ] },
        { "cabsf", [ "z" ] },
        { "cabsl", [ "z" ] },
        { "cacheflush", [ "addr", "nbytes", "cache" ] },
        { "cacos", [ "z" ] },
        { "cacosf", [ "z" ] },
        { "cacosh", [ "z" ] },
        { "cacoshf", [ "z" ] },
        { "cacoshl", [ "z" ] },
        { "cacosl", [ "z" ] },
        { "calloc", [ "nmemb", "size" ] },
        { "canonicalize_file_name", [ "path" ] },
        { "carg", [ "z" ] },
        { "cargf", [ "z" ] },
        { "cargl", [ "z" ] },
        { "casin", [ "z" ] },
        { "casinf", [ "z" ] },
        { "casinh", [ "z" ] },
        { "casinhf", [ "z" ] },
        { "casinhl", [ "z" ] },
        { "casinl", [ "z" ] },
        { "catan", [ "z" ] },
        { "catanf", [ "z" ] },
        { "catanh", [ "z" ] },
        { "catanhf", [ "z" ] },
        { "catanhl", [ "z" ] },
        { "catanl", [ "z" ] },
        { "catclose", [ "catalog" ] },
        { "catgets", [ "catalog", "set_number", "message_number", "message" ] },
        { "catopen", [ "name", "flag" ] },
        { "cbc_crypt", [ "key", "data", "datalen", "mode", "ivec" ] },
        { "cbrt", [ "x" ] },
        { "cbrtf", [ "x" ] },
        { "cbrtl", [ "x" ] },
        { "ccos", [ "z" ] },
        { "ccosf", [ "z" ] },
        { "ccosh", [ "z" ] },
        { "ccoshf", [ "z" ] },
        { "ccoshl", [ "z" ] },
        { "ccosl", [ "z" ] },
        { "ceil", [ "x" ] },
        { "ceilf", [ "x" ] },
        { "ceill", [ "x" ] },
        { "cexp", [ "z" ] },
        { "cexp2", [ "z" ] },
        { "cexp2f", [ "z" ] },
        { "cexp2l", [ "z" ] },
        { "cexpf", [ "z" ] },
        { "cexpl", [ "z" ] },
        { "cfgetispeed", [ "termios_p" ] },
        { "cfgetospeed", [ "termios_p" ] },
        { "cfmakeraw", [ "termios_p" ] },
        { "cfree", [ "ptr" ] },
        { "cfsetispeed", [ "termios_p", "speed" ] },
        { "cfsetospeed", [ "termios_p", "speed" ] },
        { "cfsetspeed", [ "termios_p", "speed" ] },
        { "chdir", [ "path" ] },
        { "chmod", [ "pathname", "mode" ] },
        { "chown", [ "pathname", "owner", "group" ] },
        { "chroot", [ "path" ] },
        { "cimag", [ "z" ] },
        { "cimagf", [ "z" ] },
        { "cimagl", [ "z" ] },
        { "clearerr", [ "stream" ] },
        { "clearerr_unlocked", [ "stream" ] },
        { "clock_adjtime", [ "clk_id", "buf" ] },
        { "clock_getcpuclockid", [ "pid", "clockid" ] },
        { "clock_getres", [ "clockid", "res" ] },
        { "clock_gettime", [ "clockid", "tp" ] },
        { "clock_nanosleep", [ "clockid", "flags", "request", "remain" ] },
        { "clock_settime", [ "clockid", "tp" ] },
        { "clog", [ "z" ] },
        { "clog10", [ "z" ] },
        { "clog10f", [ "z" ] },
        { "clog10l", [ "z" ] },
        { "clog2", [ "z" ] },
        { "clog2f", [ "z" ] },
        { "clog2l", [ "z" ] },
        { "clogf", [ "z" ] },
        { "clogl", [ "z" ] },
        { "clone", ["fn", "stack", "flags", "arg"] },
        { "close", [ "fd" ] },
        { "close_range", [ "first", "last", "flags" ] },
        { "closedir", [ "dirp" ] },
        { "confstr", [ "name", "buf", "size" ] },
        { "conj", [ "z" ] },
        { "conjf", [ "z" ] },
        { "conjl", [ "z" ] },
        { "connect", [ "sockfd", "addr", "addrlen" ] },
        { "copy_file_range", [ "fd_in", "off_in", "fd_out", "off_out", "len", "flags" ] },
        { "copysign", [ "x", "y" ] },
        { "copysignf", [ "x", "y" ] },
        { "copysignl", [ "x", "y" ] },
        { "cos", [ "x" ] },
        { "cosf", [ "x" ] },
        { "cosh", [ "x" ] },
        { "coshf", [ "x" ] },
        { "coshl", [ "x" ] },
        { "cosl", [ "x" ] },
        { "cpow", [ "x", "z" ] },
        { "cpowf", [ "x", "z" ] },
        { "cpowl", [ "x", "z" ] },
        { "cproj", [ "z" ] },
        { "cprojf", [ "z" ] },
        { "cprojl", [ "z" ] },
        { "creal", [ "z" ] },
        { "crealf", [ "z" ] },
        { "creall", [ "z" ] },
        { "creat", [ "pathname", "mode" ] },
        { "create_module", [ "name", "size" ] },
        { "crypt", [ "key", "salt" ] },
        { "crypt_r", [ "key", "salt", "data" ] },
        { "csin", [ "z" ] },
        { "csinf", [ "z" ] },
        { "csinh", [ "z" ] },
        { "csinhf", [ "z" ] },
        { "csinhl", [ "z" ] },
        { "csinl", [ "z" ] },
        { "csqrt", [ "z" ] },
        { "csqrtf", [ "z" ] },
        { "csqrtl", [ "z" ] },
        { "ctan", [ "z" ] },
        { "ctanf", [ "z" ] },
        { "ctanh", [ "z" ] },
        { "ctanhf", [ "z" ] },
        { "ctanhl", [ "z" ] },
        { "ctanl", [ "z" ] },
        { "ctermid", [ "s" ] },
        { "ctime", [ "timep" ] },
        { "ctime_r", [ "timep", "buf" ] },
        { "cuserid", [ "string" ] },
        { "daemon", [ "nochdir", "noclose" ] },
        { "dbopen", [ "file", "flags", "mode", "type", "openinfo" ] },
        { "des_setparity", [ "key" ] },
        { "difftime", [ "time1", "time0" ] },
        { "dirfd", [ "dirp" ] },
        { "dirname", [ "path" ] },
        { "div", [ "numerator", "denominator" ] },
        { "dladdr", [ "addr", "info" ] },
        { "dladdr1", [ "addr", "info", "extra_info", "flags" ] },
        { "dlclose", [ "handle" ] },
        { "dlmopen", [ "lmid", "filename", "flags" ] },
        { "dlopen", [ "filename", "flags" ] },
        { "dlsym", [ "handle", "symbol" ] },
        { "dlvsym", [ "handle", "symbol", "version" ] },
        { "dn_comp", [ "exp_dn", "comp_dn", "length", "dnptrs", "lastdnptr" ] },
        { "dn_expand", [ "msg", "eomorig", "comp_dn", "exp_dn", "length" ] },
        { "dprintf", [ "fd", "format" ] },
        { "drand48_r", [ "buffer", "result" ] },
        { "drem", [ "x", "y" ] },
        { "dremf", [ "x", "y" ] },
        { "dreml", [ "x", "y" ] },
        { "dup", [ "oldfd" ] },
        { "dup2", [ "oldfd", "newfd" ] },
        { "dup3", [ "oldfd", "newfd", "flags" ] },
        { "duplocale", [ "locobj" ] },
        { "dysize", [ "year" ] },
        { "eaccess", [ "pathname", "mode" ] },
        { "ecb_crypt", [ "key", "data", "datalen", "mode" ] },
        { "ecvt", [ "number", "ndigits", "decpt", "sign" ] },
        { "ecvt_r", [ "number", "ndigits", "decpt", "sign", "buf", "len" ] },
        { "encrypt", [ "block" ] },
        { "encrypt_r", [ "block", "edflag", "data" ] },
        { "endmntent", [ "streamp" ] },
        { "envz_add", [ "envz", "envz_len", "name", "value" ] },
        { "envz_entry", [ "envz", "envz_len", "name" ] },
        { "envz_get", [ "envz", "envz_len", "name" ] },
        { "envz_merge", [ "envz", "envz_len", "envz2", "envz2_len", "override" ] },
        { "envz_remove", [ "envz", "envz_len", "name" ] },
        { "envz_strip", [ "envz", "envz_len" ] },
        { "epoll_create", [ "size" ] },
        { "epoll_create1", [ "flags" ] },
        { "epoll_ctl", [ "epfd", "op", "fd", "event" ] },
        { "epoll_pwait", [ "epfd", "events", "maxevents", "timeout", "sigmask" ] },
        { "epoll_pwait2", [ "epfd", "events", "maxevents", "timeout", "sigmask" ] },
        { "epoll_wait", [ "epfd", "events", "maxevents", "timeout" ] },
        { "erand48", [ "xsubi" ] },
        { "erand48_r", [ "xsubi", "buffer", "result" ] },
        { "erf", [ "x" ] },
        { "erfc", [ "x" ] },
        { "erfcf", [ "x" ] },
        { "erfcl", [ "x" ] },
        { "erff", [ "x" ] },
        { "erfl", [ "x" ] },
        { "err", [ "eval", "fmt" ] },
        { "error", [ "status", "errnum", "format" ] },
        { "error_at_line", [ "status", "errnum", "filename", "linenum", "format" ] },
        { "errx", [ "eval", "fmt" ] },
        { "ether_aton", [ "asc" ] },
        { "ether_aton_r", [ "asc", "addr" ] },
        { "ether_hostton", [ "hostname", "addr" ] },
        { "ether_line", [ "line", "addr", "hostname" ] },
        { "ether_ntoa", [ "addr" ] },
        { "ether_ntoa_r", [ "addr", "buf" ] },
        { "ether_ntohost", [ "hostname", "addr" ] },
        { "euidaccess", [ "pathname", "mode" ] },
        { "eventfd", [ "initval", "flags" ] },
        { "eventfd_read", [ "fd", "value" ] },
        { "eventfd_write", [ "fd", "value" ] },
        { "execv", [ "pathname", "argv" ] },
        { "execve", [ "pathname", "argv", "envp" ] },
        { "execveat", [ "dirfd", "pathname", "argv", "envp", "flags" ] },
        { "execvp", [ "file", "argv" ] },
        { "execvpe", [ "file", "argv" ] },
        { "exit", [ "status" ] },
        { "exp", [ "x" ] },
        { "exp10", [ "x" ] },
        { "exp10f", [ "x" ] },
        { "exp10l", [ "x" ] },
        { "exp2", [ "x" ] },
        { "exp2f", [ "x" ] },
        { "exp2l", [ "x" ] },
        { "expf", [ "x" ] },
        { "expl", [ "x" ] },
        { "explicit_bzero", [ "s", "n" ] },
        { "expm1", [ "x" ] },
        { "expm1f", [ "x" ] },
        { "expm1l", [ "x" ] },
        { "fabs", [ "x" ] },
        { "fabsf", [ "x" ] },
        { "fabsl", [ "x" ] },
        { "faccessat", [ "dirfd", "pathname", "mode", "flags", "dirfd", "pathname", "mode", "flags" ] },
        { "fallocate", [ "fd", "mode", "offset", "len" ] },
        { "fanotify_init", [ "flags", "event_f_flags" ] },
        { "fanotify_mark", [ "fanotify_fd", "flags", "mask", "dirfd", "pathname" ] },
        { "fchdir", [ "fd" ] },
        { "fchmod", [ "fd", "mode" ] },
        { "fchmodat", [ "dirfd", "pathname", "mode", "flags" ] },
        { "fchown", [ "fd", "owner", "group" ] },
        { "fchownat", [ "dirfd", "pathname", "owner", "group", "flags" ] },
        { "fclose", [ "stream" ] },
        { "fcntl", [ "fd", "cmd" ] },
        { "fcvt", [ "number", "ndigits", "decpt", "sign" ] },
        { "fcvt_r", [ "number", "ndigits", "decpt", "sign", "buf", "len" ] },
        { "fdatasync", [ "fd" ] },
        { "fdim", [ "x", "y" ] },
        { "fdimf", [ "x", "y" ] },
        { "fdiml", [ "x", "y" ] },
        { "fdopen", [ "fd", "mode" ] },
        { "fdopendir", [ "fd" ] },
        { "feclearexcept", [ "excepts" ] },
        { "fegetenv", [ "envp" ] },
        { "fegetexceptflag", [ "flagp", "excepts" ] },
        { "feholdexcept", [ "envp" ] },
        { "feof", [ "stream" ] },
        { "feof_unlocked", [ "stream" ] },
        { "feraiseexcept", [ "excepts" ] },
        { "ferror", [ "stream" ] },
        { "ferror_unlocked", [ "stream" ] },
        { "fesetenv", [ "envp" ] },
        { "fesetexceptflag", [ "flagp", "excepts" ] },
        { "fesetround", [ "rounding_mode" ] },
        { "fetestexcept", [ "excepts" ] },
        { "feupdateenv", [ "envp" ] },
        { "fexecve", [ "fd", "argv" ] },
        { "fflush", [ "stream" ] },
        { "fflush_unlocked", [ "stream" ] },
        { "ffs", [ "i" ] },
        { "ffsl", [ "i" ] },
        { "ffsll", [ "i" ] },
        { "fgetc", [ "stream" ] },
        { "fgetc_unlocked", [ "stream" ] },
        { "fgetgrent", [ "stream" ] },
        { "fgetgrent_r", [ "stream", "gbuf", "buf", "buflen", "gbufp" ] },
        { "fgetpos", [ "stream", "pos" ] },
        { "fgetpwent", [ "stream" ] },
        { "fgetpwent_r", [ "stream", "pwbuf", "buf", "buflen", "pwbufp" ] },
        { "fgets", [ "s", "size", "stream" ] },
        { "fgets_unlocked", [ "s", "n", "stream" ] },
        { "fgetspent", [ "stream" ] },
        { "fgetspent_r", [ "stream", "spbuf", "buf", "buflen", "spbufp" ] },
        { "fgetwc", [ "stream" ] },
        { "fgetwc_unlocked", [ "stream" ] },
        { "fgetws", [ "ws", "n", "stream" ] },
        { "fgetws_unlocked", [ "ws", "n", "stream" ] },
        { "fgetxattr", [ "fd", "name", "value", "size" ] },
        { "fileno", [ "stream" ] },
        { "fileno_unlocked", [ "stream" ] },
        { "finite", [ "x" ] },
        { "finitef", [ "x" ] },
        { "finitel", [ "x" ] },
        { "flistxattr", [ "fd", "list", "size" ] },
        { "flock", [ "fd", "operation" ] },
        { "flockfile", [ "filehandle" ] },
        { "floor", [ "x" ] },
        { "floorf", [ "x" ] },
        { "floorl", [ "x" ] },
        { "fma", [ "x", "y", "z" ] },
        { "fmaf", [ "x", "y", "z" ] },
        { "fmal", [ "x", "y", "z" ] },
        { "fmax", [ "x", "y" ] },
        { "fmaxf", [ "x", "y" ] },
        { "fmaxl", [ "x", "y" ] },
        { "fmemopen", [ "buf", "size", "mode" ] },
        { "fmin", [ "x", "y" ] },
        { "fminf", [ "x", "y" ] },
        { "fminl", [ "x", "y" ] },
        { "fmod", [ "x", "y" ] },
        { "fmodf", [ "x", "y" ] },
        { "fmodl", [ "x", "y" ] },
        { "fmtmsg", [ "classification", "label", "severity", "text", "action", "tag" ] },
        { "fnmatch", [ "pattern", "string", "flags" ] },
        { "fopen", [ "pathname", "mode" ] },
        { "fopencookie", [ "cookie", "mode", "io_funcs" ] },
        { "forkpty", [ "amaster", "name", "termp", "winp" ] },
        { "fpathconf", [ "fd", "name" ] },
        { "fpclassify", [ "x" ] },
        { "fprintf", [ "stream", "format" ] },
        { "fpurge", [ "stream" ] },
        { "fputc", [ "c", "stream" ] },
        { "fputc_unlocked", [ "c", "stream" ] },
        { "fputs", [ "s", "stream" ] },
        { "fputs_unlocked", [ "s", "stream" ] },
        { "fputwc", [ "wc", "stream" ] },
        { "fputwc_unlocked", [ "wc", "stream" ] },
        { "fputws", [ "ws", "stream" ] },
        { "fputws_unlocked", [ "ws", "stream" ] },
        { "fread", [ "ptr", "nmemb", "size", "nmemb", "stream" ] },
        { "fread_unlocked", [ "ptr", "n", "size", "n", "stream" ] },
        { "free", [ "ptr" ] },
        { "freeaddrinfo", [ "res" ] },
        { "freehostent", [ "ip" ] },
        { "freeifaddrs", ["ifa" ] },
        { "freelocale", [ "locobj" ] },
        { "fremovexattr", [ "fd", "name" ] },
        { "freopen", [ "pathname", "mode", "stream" ] },
        { "frexp", [ "x", "exp" ] },
        { "frexpf", [ "x", "exp" ] },
        { "frexpl", [ "x", "exp" ] },
        { "fscanf", [ "stream", "format" ] },
        { "fseek", [ "stream", "offset", "whence" ] },
        { "fseeko", [ "stream", "offset", "whence" ] },
        { "fsetpos", [ "stream", "pos" ] },
        { "fsetxattr", [ "fd", "name", "value", "size", "flags" ] },
        { "fstat", [ "fd", "statbuf" ] },
        { "fstatat", [ "dirfd", "pathname", "statbuf", "flags" ] },
        { "fstatfs", [ "fd", "buf" ] },
        { "fstatvfs", [ "fd", "buf" ] },
        { "fsync", [ "fd" ] },
        { "ftell", [ "stream" ] },
        { "ftello", [ "stream" ] },
        { "ftime", [ "tp" ] },
        { "ftok", [ "pathname", "proj_id" ] },
        { "ftruncate", [ "fd", "length" ] },
        { "ftrylockfile", [ "filehandle" ] },
        { "fts_children", [ "ftsp", "instr" ] },
        { "fts_close", [ "ftsp" ] },
        { "fts_open", [ "path_argv", "options", "compar" ] },
        { "fts_read", [ "ftsp" ] },
        { "fts_set", [ "ftsp", "f", "instr" ] },
        { "ftw", [ "dirpath", "fn", "fpath", "sb", "typeflag", "nopenfd" ] },
        { "funlockfile", [ "filehandle" ] },
        { "futimens", [ "fd", "times" ] },
        { "futimes", [ "fd", "tv" ] },
        { "futimesat", [ "dirfd", "pathname", "times" ] },
        { "fwide", [ "stream", "mode" ] },
        { "fwprintf", [ "stream", "format" ] },
        { "fwrite", [ "ptr", "nmemb", "size", "nmemb", "stream" ] },
        { "fwrite_unlocked", [ "ptr", "n", "size", "n", "stream" ] },
        { "gai_cancel", [ "req" ] },
        { "gai_error", [ "req" ] },
        { "gai_strerror", [ "errcode" ] },
        { "gai_suspend", [ "list", "timeout" ] },
        { "gamma", [ "x" ] },
        { "gammaf", [ "x" ] },
        { "gammal", [ "x" ] },
        { "gcvt", [ "number", "ndigit", "buf" ] },
        { "get_kernel_syms", [ "table" ] },
        { "get_mempolicy", [ "mode", "nodemask", "unsigned", "void", "unsigned" ] },
        { "getaddrinfo", [ "node", "service", "hints", "res" ] },
        { "getaddrinfo_a", [ "mode", "list", "nitems", "sevp" ] },
        { "getaliasbyname", [ "name" ] },
        { "getaliasbyname_r", [ "name", "result", "buffer", "buflen", "res" ] },
        { "getaliasent_r", [ "result", "buffer", "buflen", "res" ] },
        { "getauxval", [ "type" ] },
        { "getc", [ "stream" ] },
        { "getc_unlocked", [ "stream" ] },
        { "getcontext", [ "ucp" ] },
        { "getcpu", [ "cpu", "node" ] },
        { "getcwd", [ "buf", "size" ] },
        { "getdate", [ "string" ] },
        { "getdate_r", [ "string", "res" ] },
        { "getdelim", [ "lineptr", "n", "delim", "stream" ] },
        { "getdents64", [ "fd", "dirp", "count" ] },
        { "getdirentries", [ "fd", "buf", "nbytes", "basep" ] },
        { "getdomainname", [ "name", "len" ] },
        { "getentropy", [ "buffer", "length" ] },
        { "getenv", [ "name" ] },
        { "getfsfile", [ "mount_point" ] },
        { "getfsspec", [ "special_file" ] },
        { "getgrent_r", [ "gbuf", "buf", "buflen", "gbufp" ] },
        { "getgrgid", [ "gid" ] },
        { "getgrgid_r", [ "gid", "grp", "buf", "buflen", "result" ] },
        { "getgrnam", [ "name" ] },
        { "getgrnam_r", [ "name", "grp", "buf", "buflen", "result" ] },
        { "getgrouplist", [ "user", "group", "groups", "ngroups" ] },
        { "getgroups", [ "size", "list" ] },
        { "gethostbyaddr", [ "addr", "len", "type" ] },
        { "gethostbyaddr_r", [ "addr", "len", "type", "ret", "buf", "buflen", "result", "h_errnop" ] },
        { "gethostbyname", [ "name" ] },
        { "gethostbyname2", [ "name", "af" ] },
        { "gethostbyname2_r", [ "name", "af", "ret", "buf", "buflen", "result", "h_errnop" ] },
        { "gethostbyname_r", [ "name", "ret", "buf", "buflen", "result", "h_errnop" ] },
        { "gethostent_r", [ "ret", "buf", "buflen", "result", "h_errnop" ] },
        { "gethostname", [ "name", "len" ] },
        { "getifaddrs", [ "ifap" ] },
        { "getipnodebyaddr", [ "addr", "len", "af", "flags", "error_num" ] },
        { "getipnodebyname", [ "name", "af", "flags", "error_num" ] },
        { "getitimer", [ "which", "curr_value" ] },
        { "getline", [ "lineptr", "n", "stream" ] },
        { "getloadavg", [ "loadavg", "nelem" ] },
        { "getlogin_r", [ "buf", "bufsize" ] },
        { "getmntent", [ "stream" ] },
        { "getmntent_r", [ "streamp", "mntbuf", "buf", "buflen" ] },
        { "getnameinfo", [ "addr", "addrlen", "host", "hostlen", "serv", "servlen", "flags" ] },
        { "getnetbyaddr", [ "net", "type" ] },
        { "getnetbyaddr_r", [ "net", "type", "result_buf", "buf", "buflen", "result", "h_errnop" ] },
        { "getnetbyname", [ "name" ] },
        { "getnetbyname_r", [ "name", "result_buf", "buf", "buflen", "result", "h_errnop" ] },
        { "getnetent_r", [ "result_buf", "buf", "buflen", "result", "h_errnop" ] },
        { "getnetgrent", [ "host", "user", "domain" ] },
        { "getnetgrent_r", [ "host", "user", "domain", "buf", "buflen" ] },
        { "getopt", [ "argc", "argv", "optstring" ] },
        { "getopt_long", [ "argc", "argv", "optstring", "longopts", "longindex" ] },
        { "getopt_long_only", [ "argc", "argv", "optstring", "longopts", "longindex" ] },
        { "getpass", [ "prompt" ] },
        { "getpeername", [ "sockfd", "addr", "addrlen" ] },
        { "getpgid", [ "pid" ] },
        { "getpriority", [ "which", "who" ] },
        { "getprotobyname", [ "name" ] },
        { "getprotobyname_r", [ "name", "result_buf", "buf", "buflen", "result" ] },
        { "getprotobynumber", [ "proto" ] },
        { "getprotobynumber_r", [ "proto", "result_buf", "buf", "buflen", "result" ] },
        { "getprotoent_r", [ "result_buf", "buf", "buflen", "result" ] },
        { "getpw", [ "uid", "buf" ] },
        { "getpwent_r", [ "pwbuf", "buf", "buflen", "pwbufp" ] },
        { "getpwnam", [ "name" ] },
        { "getpwnam_r", [ "name", "pwd", "buf", "buflen", "result" ] },
        { "getpwuid", [ "uid" ] },
        { "getpwuid_r", [ "uid", "pwd", "buf", "buflen", "result" ] },
        { "getrandom", [ "buf", "buflen", "flags" ] },
        { "getresgid", [ "rgid", "egid", "sgid" ] },
        { "getresuid", [ "ruid", "euid", "suid" ] },
        { "getrlimit", [ "resource", "rlim" ] },
        { "getrpcbyname", [ "name" ] },
        { "getrpcbyname_r", [ "name", "result_buf", "buf", "buflen", "result" ] },
        { "getrpcbynumber", [ "number" ] },
        { "getrpcbynumber_r", [ "number", "result_buf", "buf", "buflen", "result" ] },
        { "getrpcent_r", [ "result_buf", "buf", "buflen", "result" ] },
        { "getrpcport", [ "host", "prognum", "versnum", "proto" ] },
        { "getrusage", [ "who", "usage" ] },
        { "gets", [ "s" ] },
        { "getservbyname", [ "name", "proto" ] },
        { "getservbyname_r", [ "name", "proto", "result_buf", "buf", "buflen", "result" ] },
        { "getservbyport", [ "port", "proto" ] },
        { "getservbyport_r", [ "port", "proto", "result_buf", "buf", "buflen", "result" ] },
        { "getservent_r", [ "result_buf", "buf", "buflen", "result" ] },
        { "getsid", [ "pid" ] },
        { "getsockname", [ "sockfd", "addr", "addrlen" ] },
        { "getsockopt", [ "sockfd", "level", "optname", "optval", "optlen" ] },
        { "getspent_r", [ "spbuf", "buf", "buflen", "spbufp" ] },
        { "getspnam", [ "name" ] },
        { "getspnam_r", [ "name", "spbuf", "buf", "buflen", "spbufp" ] },
        { "getsubopt", [ "optionp", "tokens", "valuep" ] },
        { "gettimeofday", [ "tv", "tz" ] },
        { "getttynam", [ "name" ] },
        { "getutid", [ "ut" ] },
        { "getutline", [ "ut" ] },
        { "getutmp", [ "ux", "u" ] },
        { "getutmpx", [ "u", "ux" ] },
        { "getw", [ "stream" ] },
        { "getwc", [ "stream" ] },
        { "getwc_unlocked", [ "stream" ] },
        { "getwd", [ "buf" ] },
        { "getxattr", [ "path", "name", "value", "size" ] },
        { "glob", [ "pattern", "flags", "errfunc", "epath", "eerrno", "pglob" ] },
        { "globfree", [ "pglob" ] },
        { "gmtime", [ "timep" ] },
        { "gmtime_r", [ "timep", "result" ] },
        { "grantpt", [ "fd" ] },
        { "group_member", [ "gid" ] },
        { "gsignal", [ "signum" ] },
        { "hasmntopt", [ "mnt", "opt" ] },
        { "hcreate", [ "nel" ] },
        { "hcreate_r", [ "nel", "htab" ] },
        { "hdestroy_r", [ "htab" ] },
        { "herror", [ "s" ] },
        { "hsearch", [ "item", "action" ] },
        { "hsearch_r", [ "item", "action", "retval", "htab" ] },
        { "hstrerror", [ "err" ] },
        { "htobe16", [ "host_16bits" ] },
        { "htobe32", [ "host_32bits" ] },
        { "htobe64", [ "host_64bits" ] },
        { "htole16", [ "host_16bits" ] },
        { "htole32", [ "host_32bits" ] },
        { "htole64", [ "host_64bits" ] },
        { "htonl", [ "hostlong" ] },
        { "htons", [ "hostshort" ] },
        { "hypot", [ "x", "y" ] },
        { "hypotf", [ "x", "y" ] },
        { "hypotl", [ "x", "y" ] },
        { "if_freenameindex", [ "ptr" ] },
        { "if_indextoname", [ "ifindex", "ifname" ] },
        { "if_nameindex", [ "void" ] },
        { "if_nametoindex", [ "ifname" ] },
        { "ilogb", [ "x" ] },
        { "ilogbf", [ "x" ] },
        { "ilogbl", [ "x" ] },
        { "imaxabs", [ "j" ] },
        { "imaxdiv", [ "numerator", "denominator" ] },
        { "inb", [ "port" ] },
        { "inb_p", [ "port" ] },
        { "index", [ "s", "c" ] },
        { "inet_addr", [ "cp" ] },
        { "inet_aton", [ "cp", "inp" ] },
        { "inet_lnaof", [ "in" ] },
        { "inet_makeaddr", [ "net", "host" ] },
        { "inet_net_ntop", [ "af", "netp", "int", "char", "size_t" ] },
        { "inet_net_pton", [ "af", "pres", "netp", "nsize" ] },
        { "inet_netof", [ "in" ] },
        { "inet_network", [ "cp" ] },
        { "inet_ntoa", [ "in" ] },
        { "inet_ntop", [ "af", "src", "dst", "size" ] },
        { "inet_pton", [ "af", "src", "dst" ] },
        { "initgroups", [ "user", "group" ] },
        { "initstate", [ "seed", "state", "n" ] },
        { "initstate_r", [ "seed", "statebuf", "statelen", "buf" ] },
        { "inl", [ "port" ] },
        { "inl_p", [ "port" ] },
        { "innetgr", [ "netgroup", "host", "user", "domain" ] },
        { "inotify_add_watch", [ "fd", "pathname", "mask" ] },
        { "inotify_init1", [ "flags" ] },
        { "inotify_rm_watch", [ "fd", "wd" ] },
        { "insb", [ "port", "addr", "count" ] },
        { "insl", [ "port", "addr", "count" ] },
        { "insque", [ "elem", "prev" ] },
        { "insw", [ "port", "addr", "count" ] },
        { "inw", [ "port" ] },
        { "inw_p", [ "port" ] },
        { "ioctl", [ "fd", "request" ] },
        { "io_setup", [ "nr_events", "ctx_idp" ] },
        { "io_submit", [ "ctx_id", "nr", "iocbpp" ] },
        { "ioperm", [ "from", "num", "turn_on" ] },
        { "iopl", [ "level" ] },
        { "iruserok", [ "raddr", "superuser", "ruser", "luser" ] },
        { "iruserok_af", [ "raddr", "superuser", "ruser", "luser", "af" ] },
        { "isalnum", [ "c" ] },
        { "isalnum_l", [ "c", "locale" ] },
        { "isalpha", [ "c" ] },
        { "isalpha_l", [ "c", "locale" ] },
        { "isascii", [ "c" ] },
        { "isascii_l", [ "c", "locale" ] },
        { "isatty", [ "fd" ] },
        { "isblank", [ "c" ] },
        { "isblank_l", [ "c", "locale" ] },
        { "iscntrl", [ "c" ] },
        { "iscntrl_l", [ "c", "locale" ] },
        { "isdigit", [ "c" ] },
        { "isdigit_l", [ "c", "locale" ] },
        { "isfdtype", [ "fd", "fdtype" ] },
        { "isfinite", [ "x" ] },
        { "isgraph", [ "c" ] },
        { "isgraph_l", [ "c", "locale" ] },
        { "isgreater", [ "x", "y" ] },
        { "isgreaterequal", [ "x", "y" ] },
        { "isinf", [ "x" ] },
        { "isinff", [ "x" ] },
        { "isinfl", [ "x" ] },
        { "isless", [ "x", "y" ] },
        { "islessequal", [ "x", "y" ] },
        { "islessgreater", [ "x", "y" ] },
        { "islower", [ "c" ] },
        { "islower_l", [ "c", "locale" ] },
        { "isnan", [ "x" ] },
        { "isnanf", [ "x" ] },
        { "isnanl", [ "x" ] },
        { "isnormal", [ "x" ] },
        { "isprint", [ "c" ] },
        { "isprint_l", [ "c", "locale" ] },
        { "ispunct", [ "c" ] },
        { "ispunct_l", [ "c", "locale" ] },
        { "isspace", [ "c" ] },
        { "isspace_l", [ "c", "locale" ] },
        { "isunordered", [ "x", "y" ] },
        { "isupper", [ "c" ] },
        { "isupper_l", [ "c", "locale" ] },
        { "iswalnum", [ "wc" ] },
        { "iswalpha", [ "wc" ] },
        { "iswblank", [ "wc" ] },
        { "iswcntrl", [ "wc" ] },
        { "iswctype", [ "wc", "desc" ] },
        { "iswdigit", [ "wc" ] },
        { "iswgraph", [ "wc" ] },
        { "iswlower", [ "wc" ] },
        { "iswprint", [ "wc" ] },
        { "iswpunct", [ "wc" ] },
        { "iswspace", [ "wc" ] },
        { "iswupper", [ "wc" ] },
        { "iswxdigit", [ "wc" ] },
        { "isxdigit", [ "c" ] },
        { "isxdigit_l", [ "c", "locale" ] },
        { "j0", [ "x" ] },
        { "j0f", [ "x" ] },
        { "j0l", [ "x" ] },
        { "j1", [ "x" ] },
        { "j1f", [ "x" ] },
        { "j1l", [ "x" ] },
        { "jn", [ "n", "x" ] },
        { "jnf", [ "n", "x" ] },
        { "jnl", [ "n", "x" ] },
        { "jrand48", [ "xsubi" ] },
        { "jrand48_r", [ "xsubi", "buffer", "result" ] },
        { "key_decryptsession", [ "remotename", "deskey" ] },
        { "key_encryptsession", [ "remotename", "deskey" ] },
        { "key_gendes", [ "deskey" ] },
        { "key_setsecret", [ "key" ] },
        { "kill", [ "pid", "sig" ] },
        { "killpg", [ "pgrp", "sig" ] },
        { "klogctl", [ "type", "bufp", "len" ] },
        { "l64a", [ "value" ] },
        { "labs", [ "j" ] },
        { "lchown", [ "pathname", "owner", "group" ] },
        { "lcong48", [ "param" ] },
        { "lcong48_r", [ "param", "buffer" ] },
        { "ldexp", [ "x", "exp" ] },
        { "ldexpf", [ "x", "exp" ] },
        { "ldexpl", [ "x", "exp" ] },
        { "ldiv", [ "numerator", "denominator" ] },
        { "le16toh", [ "little_endian_16bits" ] },
        { "le32toh", [ "little_endian_32bits" ] },
        { "le64toh", [ "little_endian_64bits" ] },
        { "lfind", [ "key", "base", "nmemb", "nmemb", "size", "compar", "size", "size" ] },
        { "lgamma", [ "x" ] },
        { "lgamma_r", [ "x", "signp" ] },
        { "lgammaf", [ "x" ] },
        { "lgammaf_r", [ "x", "signp" ] },
        { "lgammal", [ "x" ] },
        { "lgammal_r", [ "x", "signp" ] },
        { "lgetxattr", [ "path", "name", "value", "size" ] },
        { "link", [ "oldpath", "newpath" ] },
        { "linkat", [ "olddirfd", "oldpath", "newdirfd", "newpath", "flags" ] },
        { "lio_listio", [ "mode", "aiocb_list", "nitems", "sevp" ] },
        { "listen", [ "sockfd", "backlog" ] },
        { "listxattr", [ "path", "list", "size" ] },
        { "llabs", [ "j" ] },
        { "lldiv", [ "numerator", "denominator" ] },
        { "llistxattr", [ "path", "list", "size" ] },
        { "llrint", [ "x" ] },
        { "llrintf", [ "x" ] },
        { "llrintl", [ "x" ] },
        { "llround", [ "x" ] },
        { "llroundf", [ "x" ] },
        { "llroundl", [ "x" ] },
        { "localtime", [ "timep" ] },
        { "localtime_r", [ "timep", "result" ] },
        { "lockf", [ "fd", "cmd", "len" ] },
        { "log", [ "x" ] },
        { "log10", [ "x" ] },
        { "log10f", [ "x" ] },
        { "log10l", [ "x" ] },
        { "log1p", [ "x" ] },
        { "log1pf", [ "x" ] },
        { "log1pl", [ "x" ] },
        { "log2", [ "x" ] },
        { "log2f", [ "x" ] },
        { "log2l", [ "x" ] },
        { "logb", [ "x" ] },
        { "logbf", [ "x" ] },
        { "logbl", [ "x" ] },
        { "logf", [ "x" ] },
        { "login", [ "ut" ] },
        { "login_tty", [ "fd" ] },
        { "logl", [ "x" ] },
        { "logout", [ "ut_line" ] },
        { "logwtmp", [ "line", "name", "host" ] },
        { "longjmp", [ "env", "val" ] },
        { "lrand48_r", [ "buffer", "result" ] },
        { "lremovexattr", [ "path", "name" ] },
        { "lrint", [ "x" ] },
        { "lrintf", [ "x" ] },
        { "lrintl", [ "x" ] },
        { "lround", [ "x" ] },
        { "lroundf", [ "x" ] },
        { "lroundl", [ "x" ] },
        { "lsearch", [ "key", "base", "nmemb", "nmemb", "size", "compar", "size", "size" ] },
        { "lseek", [ "fd", "offset", "whence" ] },
        { "lseek64", [ "fd", "offset", "whence" ] },
        { "lsetxattr", [ "path", "name", "value", "size", "flags" ] },
        { "lstat", [ "pathname", "statbuf" ] },
        { "lutimes", [ "filename", "tv" ] },
        { "madvise", [ "addr", "length", "advice" ] },
        { "major", [ "dev" ] },
        { "makecontext", ["ucp", "func", "argc"]},
        { "makedev", [ "maj", "min" ] },
        { "malloc", [ "size" ] },
        { "malloc_info", [ "options", "stream" ] },
        { "malloc_set_state", [ "state" ] },
        { "malloc_trim", [ "pad" ] },
        { "malloc_usable_size", [ "ptr" ] },
        { "mallopt", [ "param", "value" ] },
        { "matherr", [ "exc" ] },
        { "mbind", [ "addr", "len", "mode", "nodemask", "unsigned", "unsigned" ] },
        { "mblen", [ "s", "n" ] },
        { "mbrlen", [ "s", "n", "ps" ] },
        { "mbrtowc", [ "pwc", "s", "n", "ps" ] },
        { "mbsinit", [ "ps" ] },
        { "mbsnrtowcs", [ "dest", "src", "nms", "len", "ps" ] },
        { "mbsrtowcs", [ "dest", "src", "len", "ps" ] },
        { "mbstowcs", [ "dest", "src", "n" ] },
        { "mbtowc", [ "pwc", "s", "n" ] },
        { "mcheck", [ "abortfunc", "mstatus" ] },
        { "mcheck_pedantic", [ "abortfunc", "mstatus" ] },
        { "memalign", [ "alignment", "size" ] },
        { "memccpy", [ "dest", "src", "c", "n" ] },
        { "memchr", [ "s", "c", "n" ] },
        { "memcmp", [ "s1", "s2", "n" ] },
        { "memcpy", [ "dest", "src", "n" ] },
        { "memfd_create", [ "name", "flags" ] },
        { "memfrob", [ "s", "n" ] },
        { "memmem", [ "haystack", "haystacklen", "needle", "needlelen" ] },
        { "memmove", [ "dest", "src", "n" ] },
        { "mempcpy", [ "dest", "src", "n" ] },
        { "memrchr", [ "s", "c", "n" ] },
        { "memset", [ "s", "c", "n" ] },
        { "migrate_pages", [ "pid", "maxnode", "old_nodes", "new_nodes" ] },
        { "mincore", [ "addr", "length", "vec" ] },
        { "minor", [ "dev" ] },
        { "mkdir", [ "pathname", "mode" ] },
        { "mkdirat", [ "dirfd", "pathname", "mode" ] },
        { "mkdtemp", [ "template" ] },
        { "mkfifo", [ "pathname", "mode" ] },
        { "mkfifoat", [ "dirfd", "pathname", "mode" ] },
        { "mknod", [ "pathname", "mode", "dev" ] },
        { "mknodat", [ "dirfd", "pathname", "mode", "dev" ] },
        { "mkostemp", [ "template", "flags" ] },
        { "mkostemps", [ "template", "suffixlen", "flags" ] },
        { "mkstemp", [ "template" ] },
        { "mkstemps", [ "template", "suffixlen" ] },
        { "mktemp", [ "template" ] },
        { "mktime", [ "tm" ] },
        { "mlock", [ "addr", "len" ] },
        { "mlock2", [ "addr", "len", "flags" ] },
        { "mlockall", [ "flags" ] },
        { "mmap", [ "addr", "length", "prot", "flags", "fd", "offset" ] },
        { "modf", [ "x", "iptr" ] },
        { "modff", [ "x", "iptr" ] },
        { "modfl", [ "x", "iptr" ] },
        { "mount", [ "source", "target", "filesystemtype", "mountflags", "data" ] },
        { "move_pages", [ "pid", "count", "pages", "nodes", "status", "flags" ] },
        { "mpool_close", [ "mp" ] },
        { "mpool_filter", [ "mp", "void", "void", "pgcookie" ] },
        { "mpool_get", [ "mp", "pgno", "flags" ] },
        { "mpool_new", [ "mp", "pgnoaddr" ] },
        { "mpool_open", [ "key", "fd", "pagesize", "maxcache" ] },
        { "mpool_put", [ "mp", "pgaddr", "flags" ] },
        { "mpool_sync", [ "mp" ] },
        { "mprobe", [ "ptr" ] },
        { "mprotect", [ "addr", "len", "prot" ] },
        { "mq_open", [ "name", "oflag"]},
        { "mq_close", [ "mqdes" ] },
        { "mq_getattr", [ "mqdes", "attr" ] },
        { "mq_notify", [ "mqdes", "sevp" ] },
        { "mq_receive", [ "mqdes", "msg_ptr", "msg_len", "msg_prio" ] },
        { "mq_send", [ "mqdes", "msg_ptr", "msg_len", "msg_prio" ] },
        { "mq_setattr", [ "mqdes", "newattr", "oldattr" ] },
        { "mq_timedreceive", [ "mqdes", "msg_ptr", "msg_len", "msg_prio", "abs_timeout" ] },
        { "mq_timedsend", [ "mqdes", "msg_ptr", "msg_len", "msg_prio", "abs_timeout" ] },
        { "mq_unlink", [ "name" ] },
        { "mrand48_r", [ "buffer", "result" ] },
        { "mremap", ["old_address", "old_size", "new_size", "flags"]},
        { "msgctl", [ "msqid", "cmd", "buf" ] },
        { "msgget", [ "key", "msgflg" ] },
        { "msgrcv", [ "msqid", "msgp", "msgsz", "msgtyp", "msgflg" ] },
        { "msgsnd", [ "msqid", "msgp", "msgsz", "msgflg" ] },
        { "msync", [ "addr", "length", "flags" ] },
        { "munlock", [ "addr", "len" ] },
        { "munmap", [ "addr", "length" ] },
        { "name_to_handle_at", [ "dirfd", "pathname", "handle", "mount_id", "flags" ] },
        { "nan", [ "tagp" ] },
        { "nanf", [ "tagp" ] },
        { "nanl", [ "tagp" ] },
        { "nanosleep", [ "req", "rem" ] },
        { "nearbyint", [ "x" ] },
        { "nearbyintf", [ "x" ] },
        { "nearbyintl", [ "x" ] },
        { "newlocale", [ "category_mask", "locale", "base" ] },
        { "nextafter", [ "x", "y" ] },
        { "nextafterf", [ "x", "y" ] },
        { "nextafterl", [ "x", "y" ] },
        { "nextdown", [ "x" ] },
        { "nextdownf", [ "x" ] },
        { "nextdownl", [ "x" ] },
        { "nexttoward", [ "x", "y" ] },
        { "nexttowardf", [ "x", "y" ] },
        { "nexttowardl", [ "x", "y" ] },
        { "nextup", [ "x" ] },
        { "nextupf", [ "x" ] },
        { "nextupl", [ "x" ] },
        { "nfsservctl", [ "cmd", "argp", "resp" ] },
        { "nftw", [ "dirpath", "fn", "fpath", "sb", "typeflag", "ftwbuf", "nopenfd", "flags" ] },
        { "nice", [ "inc" ] },
        { "nl_langinfo", [ "item" ] },
        { "nl_langinfo_l", [ "item", "locale" ] },
        { "nrand48", [ "xsubi" ] },
        { "nrand48_r", [ "xsubi", "buffer", "result" ] },
        { "ntohl", [ "netlong" ] },
        { "ntohs", [ "netshort" ] },
        { "ntp_adjtime", [ "buf" ] },
        { "ntp_gettime", [ "ntv" ] },
        { "ntp_gettimex", [ "ntv" ] },
        { "offsetof", [ "type", "member" ] },
        { "on_exit", [ "function", "arg" ] },
        { "open", ["pathname", "flags" ] },
        { "open_by_handle_at", [ "mount_fd", "handle", "flags" ] },
        { "open_memstream", [ "ptr", "sizeloc" ] },
        { "open_wmemstream", [ "ptr", "sizeloc" ] },
        { "openat", [ "dirfd", "pathname", "how", "flags" ] },
        { "openat2", [ "dirfd", "pathname", "how", "size" ] },
        { "opendir", [ "name" ] },
        { "openlog", [ "ident", "option", "facility" ] },
        { "openpty", [ "amaster", "aslave", "name", "termp", "winp" ] },
        { "outb", [ "value", "port" ] },
        { "outb_p", [ "value", "port" ] },
        { "outl", [ "value", "port" ] },
        { "outl_p", [ "value", "port" ] },
        { "outsb", [ "port", "addr", "count" ] },
        { "outsl", [ "port", "addr", "count" ] },
        { "outsw", [ "port", "addr", "count" ] },
        { "outw", [ "value", "port" ] },
        { "outw_p", [ "value", "port" ] },
        { "passwd2des", [ "passwd", "key" ] },
        { "pathconf", [ "path", "name" ] },
        { "pciconfig_iobase", [ "which", "bus", "devfn" ] },
        { "pciconfig_read", [ "bus", "dfn", "off", "len", "buf" ] },
        { "pciconfig_write", [ "bus", "dfn", "off", "len", "buf" ] },
        { "pclose", [ "stream" ] },
        { "perfmonctl", [ "fd", "cmd", "arg", "narg" ] },
        { "perror", [ "s" ] },
        { "personality", [ "persona" ] },
        { "pipe", [ "pipefd" ] },
        { "pipe2", [ "pipefd" ] },
        { "pkey_alloc", [ "flags", "access_rights" ] },
        { "pkey_free", [ "pkey" ] },
        { "pkey_mprotect", [ "addr", "len", "prot", "pkey" ] },
        { "poll", [ "fds", "nfds", "timeout" ] },
        { "popen", [ "command", "type" ] },
        { "posix_fadvise", [ "fd", "offset", "len", "advice" ] },
        { "posix_fallocate", [ "fd", "offset", "len" ] },
        { "posix_madvise", [ "addr", "len", "advice" ] },
        { "posix_memalign", [ "memptr", "alignment", "size" ] },
        { "posix_openpt", [ "flags" ] },
        { "posix_spawn", [ "pid", "path", "file_actions", "attrp", "argv", "envp" ] },
        { "posix_spawnp", [ "pid", "file", "file_actions", "attrp", "argv", "envp" ] },
        { "pow", [ "x", "y" ] },
        { "pow10", [ "x" ] },
        { "pow10f", [ "x" ] },
        { "pow10l", [ "x" ] },
        { "powerof2", [ "x" ] },
        { "powf", [ "x", "y" ] },
        { "powl", [ "x", "y" ] },
        { "ppoll", [ "fds", "nfds", "tmo_p", "sigmask" ] },
        { "prctl", [ "option" ] },
        { "pread", [ "fd", "buf", "count", "offset" ] },
        { "preadv", [ "fd", "iov", "iovcnt", "offset" ] },
        { "preadv2", [ "fd", "iov", "iovcnt", "offset", "flags" ] },
        { "printf", [ "format" ] },
        { "prlimit", [ "pid", "resource", "new_limit", "old_limit" ] },
        { "process_vm_readv", [ "pid", "local_iov", "liovcnt", "remote_iov", "riovcnt", "flags" ] },
        { "process_vm_writev", [ "pid", "local_iov", "liovcnt", "remote_iov", "riovcnt", "flags" ] },
        { "profil", [ "buf", "bufsiz", "offset", "scale" ] },
        { "pselect", [ "nfds", "readfds", "writefds", "exceptfds", "timeout", "sigmask" ] },
        { "psiginfo", [ "pinfo", "s" ] },
        { "psignal", [ "sig", "s" ] },
        { "pthread_atfork", [ "prepare", "parent", "void", "void" ] },
        { "pthread_attr_destroy", [ "attr" ] },
        { "pthread_attr_getaffinity_np", [ "attr", "cpusetsize", "cpuset" ] },
        { "pthread_attr_getdetachstate", [ "attr", "detachstate" ] },
        { "pthread_attr_getguardsize", [ "attr", "guardsize" ] },
        { "pthread_attr_getinheritsched", [ "attr", "inheritsched" ] },
        { "pthread_attr_getschedparam", [ "attr", "param" ] },
        { "pthread_attr_getschedpolicy", [ "attr", "policy" ] },
        { "pthread_attr_getscope", [ "attr", "scope" ] },
        { "pthread_attr_getsigmask_np", [ "attr", "sigmask" ] },
        { "pthread_attr_getstack", [ "attr", "stackaddr", "stacksize" ] },
        { "pthread_attr_getstackaddr", [ "attr", "stackaddr" ] },
        { "pthread_attr_getstacksize", [ "attr", "stacksize" ] },
        { "pthread_attr_init", [ "attr" ] },
        { "pthread_attr_setaffinity_np", [ "attr", "cpusetsize", "cpuset" ] },
        { "pthread_attr_setdetachstate", [ "attr", "detachstate" ] },
        { "pthread_attr_setguardsize", [ "attr", "guardsize" ] },
        { "pthread_attr_setinheritsched", [ "attr", "inheritsched" ] },
        { "pthread_attr_setschedparam", [ "attr", "param" ] },
        { "pthread_attr_setschedpolicy", [ "attr", "policy" ] },
        { "pthread_attr_setscope", [ "attr", "scope" ] },
        { "pthread_attr_setsigmask_np", [ "attr", "sigmask" ] },
        { "pthread_attr_setstack", [ "attr", "stackaddr", "stacksize" ] },
        { "pthread_attr_setstackaddr", [ "attr", "stackaddr" ] },
        { "pthread_attr_setstacksize", [ "attr", "stacksize" ] },
        { "pthread_cancel", [ "thread" ] },
        { "pthread_cleanup_pop", [ "execute" ] },
        { "pthread_cleanup_pop_restore_np", [ "execute" ] },
        { "pthread_cleanup_push", [ "routine", "arg" ] },
        { "pthread_cleanup_push_defer_np", [ "routine", "arg" ] },
        { "pthread_create", [ "thread", "attr", "start_routine", "void" ] },
        { "pthread_detach", [ "thread" ] },
        { "pthread_equal", [ "t1", "t2" ] },
        { "pthread_exit", [ "retval" ] },
        { "pthread_getaffinity_np", [ "thread", "cpusetsize", "cpuset" ] },
        { "pthread_getattr_default_np", [ "attr" ] },
        { "pthread_getattr_np", [ "thread", "attr" ] },
        { "pthread_getconcurrency", [ "void" ] },
        { "pthread_getcpuclockid", [ "thread", "clockid" ] },
        { "pthread_getname_np", [ "thread", "name", "size" ] },
        { "pthread_getschedparam", [ "thread", "policy", "param" ] },
        { "pthread_join", [ "thread", "retval" ] },
        { "pthread_kill", [ "thread", "sig" ] },
        { "pthread_mutex_consistent", [ "mutex" ] },
        { "pthread_mutexattr_destroy", [ "attr" ] },
        { "pthread_mutexattr_getrobust", [ "attr", "robustness" ] },
        { "pthread_mutexattr_init", [ "attr" ] },
        { "pthread_mutexattr_setrobust", [ "attr", "robustness" ] },
        { "pthread_rwlockattr_setkind_np", [ "attr", "pref", "attr", "pref" ] },
        { "pthread_setaffinity_np", [ "thread", "cpusetsize", "cpuset" ] },
        { "pthread_setattr_default_np", [ "attr" ] },
        { "pthread_setcancelstate", [ "state", "oldstate" ] },
        { "pthread_setcanceltype", [ "type", "oldtype" ] },
        { "pthread_setconcurrency", [ "new_level" ] },
        { "pthread_setname_np", [ "thread", "name" ] },
        { "pthread_setschedparam", [ "thread", "policy", "param" ] },
        { "pthread_setschedprio", [ "thread", "prio" ] },
        { "pthread_sigmask", [ "how", "set", "oldset" ] },
        { "pthread_sigqueue", [ "thread", "sig", "value" ] },
        { "pthread_spin_destroy", [ "lock" ] },
        { "pthread_spin_init", [ "lock", "pshared" ] },
        { "pthread_spin_lock", [ "lock" ] },
        { "pthread_spin_trylock", [ "lock" ] },
        { "pthread_spin_unlock", [ "lock" ] },
        { "pthread_timedjoin_np", [ "thread", "retval", "abstime" ] },
        { "pthread_tryjoin_np", [ "thread", "retval" ] },
        { "ptrace", [ "request", "pid", "addr", "data" ] },
        { "ptsname", [ "fd" ] },
        { "ptsname_r", [ "fd", "buf", "buflen" ] },
        { "putc", [ "c", "stream" ] },
        { "putc_unlocked", [ "c", "stream" ] },
        { "putchar", [ "c" ] },
        { "putchar_unlocked", [ "c" ] },
        { "putenv", [ "string" ] },
        { "putgrent", [ "grp", "stream" ] },
        { "putpwent", [ "p", "stream" ] },
        { "puts", [ "s" ] },
        { "putspent", [ "p", "stream" ] },
        { "pututline", [ "ut" ] },
        { "putw", [ "w", "stream" ] },
        { "putwc", [ "wc", "stream" ] },
        { "putwc_unlocked", [ "wc", "stream" ] },
        { "putwchar", [ "wc" ] },
        { "putwchar_unlocked", [ "wc" ] },
        { "pvalloc", [ "size" ] },
        { "pwrite", [ "fd", "buf", "count", "offset" ] },
        { "pwritev", [ "fd", "iov", "iovcnt", "offset" ] },
        { "pwritev2", [ "fd", "iov", "iovcnt", "offset", "flags" ] },
        { "qecvt", [ "number", "ndigits", "decpt", "sign" ] },
        { "qecvt_r", [ "number", "ndigits", "decpt", "sign", "buf", "len" ] },
        { "qfcvt", [ "number", "ndigits", "decpt", "sign" ] },
        { "qfcvt_r", [ "number", "ndigits", "decpt", "sign", "buf", "len" ] },
        { "qgcvt", [ "number", "ndigit", "buf" ] },
        { "qsort", [ "base", "nmemb", "nmemb", "size", "compar", "size", "size" ] },
        { "qsort_r", [ "base", "nmemb", "size", "compar", "arg" ] },
        { "query_module", [ "name", "which", "buf", "bufsize", "ret" ] },
        { "quotactl", [ "cmd", "special", "id", "addr" ] },
        { "raise", [ "sig" ] },
        { "rand_r", [ "seedp" ] },
        { "random_r", [ "buf", "result" ] },
        { "rawmemchr", [ "s", "c" ] },
        { "rcmd", [ "ahost", "inport", "locuser", "remuser", "cmd", "fd2p" ] },
        { "rcmd_af", [ "ahost", "inport", "locuser", "remuser", "cmd", "fd2p", "af" ] },
        { "re_comp", [ "regex" ] },
        { "re_exec", [ "string" ] },
        { "read", [ "fd", "buf", "count" ] },
        { "readahead", [ "fd", "offset", "count" ] },
        { "readdir", [ "dirp" ] },
        { "readdir_r", [ "dirp", "entry", "result" ] },
        { "readlink", [ "pathname", "buf", "bufsiz" ] },
        { "readlinkat", [ "dirfd", "pathname", "buf", "bufsiz" ] },
        { "readv", [ "fd", "iov", "iovcnt" ] },
        { "realloc", [ "ptr", "size" ] },
        { "reallocarray", [ "ptr", "nmemb", "size" ] },
        { "realpath", [ "path", "resolved_path" ] },
        { "reboot", [ "cmd" ] },
        { "recv", [ "sockfd", "buf", "len", "flags" ] },
        { "recvfrom", [ "sockfd", "buf", "len", "flags", "src_addr", "addrlen" ] },
        { "recvmmsg", [ "sockfd", "msgvec", "vlen", "flags", "timeout" ] },
        { "recvmsg", [ "sockfd", "msg", "flags" ] },
        { "regcomp", [ "preg", "regex", "cflags" ] },
        { "regerror", [ "errcode", "preg", "errbuf", "errbuf_size" ] },
        { "regexec", [ "preg", "string", "nmatch", "pmatch", "eflags" ] },
        { "regfree", [ "preg" ] },
        { "remainder", [ "x", "y" ] },
        { "remainderf", [ "x", "y" ] },
        { "remainderl", [ "x", "y" ] },
        { "remap_file_pages", [ "addr", "size", "prot", "pgoff", "flags" ] },
        { "remove", [ "pathname" ] },
        { "removexattr", [ "path", "name" ] },
        { "remque", [ "elem" ] },
        { "remquo", [ "x", "y", "quo" ] },
        { "remquof", [ "x", "y", "quo" ] },
        { "remquol", [ "x", "y", "quo" ] },
        { "rename", [ "oldpath", "newpath" ] },
        { "renameat", [ "olddirfd", "oldpath", "newdirfd", "newpath" ] },
        { "renameat2", [ "olddirfd", "oldpath", "newdirfd", "newpath", "flags" ] },
        { "request_key", [ "type", "description", "callout_info", "dest_keyring" ] },
        { "res_mkquery", [ "op", "dname", "class", "type", "data", "datalen", "newrr", "buf", "buflen" ] },
        { "res_nclose", [ "statep" ] },
        { "res_ninit", [ "statep" ] },
        { "res_nmkquery", [ "statep", "op", "dname", "class", "type", "data", "datalen", "newrr", "buf", "buflen" ] },
        { "res_nquery", [ "statep", "dname", "class", "type", "answer", "anslen" ] },
        { "res_nquerydomain", [ "statep", "name", "domain", "class", "type", "answer", "anslen" ] },
        { "res_nsearch", [ "statep", "dname", "class", "type", "answer", "anslen" ] },
        { "res_nsend", [ "statep", "msg", "msglen", "answer", "anslen" ] },
        { "res_query", [ "dname", "class", "type", "answer", "anslen" ] },
        { "res_querydomain", [ "name", "domain", "class", "type", "answer", "anslen" ] },
        { "res_search", [ "dname", "class", "type", "answer", "anslen" ] },
        { "res_send", [ "msg", "msglen", "answer", "anslen" ] },
        { "rewind", [ "stream" ] },
        { "rewinddir", [ "dirp" ] },
        { "rexec", [ "ahost", "inport", "user", "passwd", "cmd", "fd2p" ] },
        { "rexec_af", [ "ahost", "inport", "user", "passwd", "cmd", "fd2p", "af" ] },
        { "rindex", [ "s", "c" ] },
        { "rint", [ "x" ] },
        { "rintf", [ "x" ] },
        { "rintl", [ "x" ] },
        { "rmdir", [ "pathname" ] },
        { "round", [ "x" ] },
        { "roundf", [ "x" ] },
        { "roundl", [ "x" ] },
        { "rpmatch", [ "response" ] },
        { "rresvport", [ "port" ] },
        { "rresvport_af", [ "port", "af" ] },
        { "rtime", [ "addrp", "timep", "timeout" ] },
        { "ruserok", [ "rhost", "superuser", "ruser", "luser" ] },
        { "ruserok_af", [ "rhost", "superuser", "ruser", "luser", "af" ] },
        { "sbrk", [ "increment" ] },
        { "scalb", [ "x", "exp" ] },
        { "scalbf", [ "x", "exp" ] },
        { "scalbl", [ "x", "exp" ] },
        { "scalbln", [ "x", "exp" ] },
        { "scalblnf", [ "x", "exp" ] },
        { "scalblnl", [ "x", "exp" ] },
        { "scalbn", [ "x", "exp" ] },
        { "scalbnf", [ "x", "exp" ] },
        { "scalbnl", [ "x", "exp" ] },
        { "scanf", [ "format" ] },
        { "sched_get_priority_max", [ "policy" ] },
        { "sched_get_priority_min", [ "policy" ] },
        { "sched_getaffinity", [ "pid", "cpusetsize", "mask" ] },
        { "sched_getparam", [ "pid", "param" ] },
        { "sched_getscheduler", [ "pid" ] },
        { "sched_rr_get_interval", [ "pid", "tp" ] },
        { "sched_setaffinity", [ "pid", "cpusetsize", "mask" ] },
        { "sched_setparam", [ "pid", "param" ] },
        { "sched_setscheduler", [ "pid", "policy", "param" ] },
        { "seccomp", [ "operation", "flags", "args" ] },
        { "secure_getenv", [ "name" ] },
        { "seed48", [ "seed16v" ] },
        { "seed48_r", [ "seed16v", "buffer" ] },
        { "seekdir", [ "dirp", "loc" ] },
        { "select", [ "nfds", "readfds", "writefds", "exceptfds", "timeout" ] },
        { "sem_close", [ "sem" ] },
        { "sem_destroy", [ "sem" ] },
        { "sem_getvalue", [ "sem", "sval" ] },
        { "sem_init", [ "sem", "pshared", "value" ] },
        { "sem_open", [ "name", "oflag" ] },
        { "sem_post", [ "sem" ] },
        { "sem_timedwait", [ "sem", "abs_timeout" ] },
        { "sem_trywait", [ "sem" ] },
        { "sem_unlink", [ "name" ] },
        { "sem_wait", [ "sem" ] },
        { "semctl", ["semid", "semnum", "cmd"]},
        { "semop", [ "semid", "sops", "nsops" ] },
        { "semtimedop", [ "semid", "sops", "nsops", "timeout" ] },
        { "send", [ "sockfd", "buf", "len", "flags" ] },
        { "sendfile", [ "out_fd", "in_fd", "offset", "count" ] },
        { "sendmmsg", [ "sockfd", "msgvec", "vlen", "flags" ] },
        { "sendmsg", [ "sockfd", "msg", "flags" ] },
        { "sendto", [ "sockfd", "buf", "len", "flags", "dest_addr", "addrlen" ] },
        { "set_mempolicy", [ "mode", "nodemask", "maxnode" ] },
        { "setbuf", [ "stream", "buf" ] },
        { "setbuffer", [ "stream", "buf", "size" ] },
        { "setcontext", [ "ucp" ] },
        { "setdomainname", [ "name", "len" ] },
        { "setegid", [ "egid" ] },
        { "setenv", [ "name", "value", "overwrite" ] },
        { "seteuid", [ "euid" ] },
        { "setfsgid", [ "fsgid" ] },
        { "setfsuid", [ "fsuid" ] },
        { "setgid", [ "gid" ] },
        { "setgroups", [ "size", "list" ] },
        { "sethostent", [ "stayopen" ] },
        { "sethostid", [ "hostid" ] },
        { "sethostname", [ "name", "len" ] },
        { "setitimer", [ "which", "new_value", "old_value" ] },
        { "setjmp", [ "env" ] },
        { "setkey", [ "key" ] },
        { "setkey_r", [ "key", "data" ] },
        { "setlinebuf", [ "stream" ] },
        { "setlocale", [ "category", "locale" ] },
        { "setlogmask", [ "mask" ] },
        { "setmntent", [ "filename", "type" ] },
        { "setnetent", [ "stayopen" ] },
        { "setnetgrent", [ "netgroup" ] },
        { "setns", [ "fd", "nstype" ] },
        { "setpgid", [ "pid", "pgid" ] },
        { "setpriority", [ "which", "who", "prio" ] },
        { "setprotoent", [ "stayopen" ] },
        { "setregid", [ "rgid", "egid" ] },
        { "setresgid", [ "rgid", "egid", "sgid" ] },
        { "setresuid", [ "ruid", "euid", "suid" ] },
        { "setreuid", [ "ruid", "euid" ] },
        { "setrlimit", [ "resource", "rlim" ] },
        { "setrpcent", [ "stayopen" ] },
        { "setservent", [ "stayopen" ] },
        { "setsockopt", [ "sockfd", "level", "optname", "optval", "optlen" ] },
        { "setstate", [ "state" ] },
        { "setstate_r", [ "statebuf", "buf" ] },
        { "settimeofday", [ "tv", "tz" ] },
        { "setuid", [ "uid" ] },
        { "setvbuf", [ "stream", "buf", "mode", "size" ] },
        { "setxattr", [ "path", "name", "value", "size", "flags" ] },
        { "sgetspent", [ "s" ] },
        { "sgetspent_r", [ "s", "spbuf", "buf", "buflen", "spbufp" ] },
        { "shm_open", [ "name", "oflag", "mode" ] },
        { "shm_unlink", [ "name" ] },
        { "shmat", [ "shmid", "shmaddr", "shmflg" ] },
        { "shmctl", [ "shmid", "cmd", "buf" ] },
        { "shmdt", [ "shmaddr" ] },
        { "shmget", [ "key", "size", "shmflg" ] },
        { "shutdown", [ "sockfd", "how" ] },
        { "sigabbrev_np", [ "sig" ] },
        { "sigaction", [ "signum", "act", "oldact" ] },
        { "sigaddset", [ "set", "signum" ] },
        { "sigaltstack", [ "ss", "old_ss" ] },
        { "sigblock", [ "mask" ] },
        { "sigdelset", [ "set", "signum" ] },
        { "sigdescr_np", [ "sig" ] },
        { "sigemptyset", [ "set" ] },
        { "sigfillset", [ "set" ] },
        { "sighold", [ "sig" ] },
        { "sigignore", [ "sig" ] },
        { "siginterrupt", [ "sig", "flag" ] },
        { "sigismember", [ "set", "signum" ] },
        { "siglongjmp", [ "env", "val" ] },
        { "sigmask", [ "signum" ] },
        { "signal", [ "signum", "handler" ] },
        { "signalfd", [ "fd", "mask", "flags" ] },
        { "signbit", [ "x" ] },
        { "significand", [ "x" ] },
        { "significandf", [ "x" ] },
        { "significandl", [ "x" ] },
        { "sigpending", [ "set" ] },
        { "sigprocmask", [ "how", "set", "oldset" ] },
        { "sigqueue", [ "pid", "sig", "value" ] },
        { "sigrelse", [ "sig" ] },
        { "sigset", [ "sig", "disp" ] },
        { "sigsetjmp", [ "env", "savesigs" ] },
        { "sigsetmask", [ "mask" ] },
        { "sigsuspend", [ "mask" ] },
        { "sigtimedwait", [ "set", "info", "timeout" ] },
        { "sigvec", [ "sig", "vec", "ovec" ] },
        { "sigwait", [ "set", "sig" ] },
        { "sigwaitinfo", [ "set", "info" ] },
        { "sin", [ "x" ] },
        { "sincos", [ "x", "sin", "cos" ] },
        { "sincosf", [ "x", "sin", "cos" ] },
        { "sincosl", [ "x", "sin", "cos" ] },
        { "sinf", [ "x" ] },
        { "sinh", [ "x" ] },
        { "sinhf", [ "x" ] },
        { "sinhl", [ "x" ] },
        { "sinl", [ "x" ] },
        { "sleep", [ "seconds" ] },
        { "snprintf", [ "str", "size", "format" ] },
        { "sockatmark", [ "sockfd" ] },
        { "socket", [ "domain", "type", "protocol" ] },
        { "socketpair", [ "domain", "type", "protocol", "sv" ] },
        { "splice", [ "fd_in", "off_in", "fd_out", "off_out", "len", "flags" ] },
        { "sprintf", [ "str", "format" ] },
        { "sqrt", [ "x" ] },
        { "sqrtf", [ "x" ] },
        { "sqrtl", [ "x" ] },
        { "srand", [ "seed" ] },
        { "srand48", [ "seedval" ] },
        { "srand48_r", [ "seedval", "buffer" ] },
        { "srandom", [ "seed" ] },
        { "srandom_r", [ "seed", "buf" ] },
        { "sscanf", [ "str", "format" ] },
        { "ssignal", [ "signum", "action" ] },
        { "stat", [ "pathname", "statbuf" ] },
        { "statfs", [ "path", "buf" ] },
        { "static_assert", [ "constant", "msg" ] },
        { "statvfs", [ "path", "buf" ] },
        { "statx", [ "dirfd", "pathname", "flags", "mask", "statxbuf" ] },
        { "stime", [ "t" ] },
        { "stpcpy", [ "dst", "src" ] },
        { "stpncpy", [ "dst", "src", "sz" ] },
        { "strcasecmp", [ "s1", "s2" ] },
        { "strcasestr", [ "haystack", "needle" ] },
        { "strcat", [ "dst", "src" ] },
        { "strchr", [ "s", "c" ] },
        { "strchrnul", [ "s", "c" ] },
        { "strcmp", [ "s1", "s2" ] },
        { "strcoll", [ "s1", "s2" ] },
        { "strcpy", [ "dst", "src" ] },
        { "strcspn", [ "s", "reject" ] },
        { "strdup", [ "s" ] },
        { "strdupa", [ "s" ] },
        { "strerror", [ "errnum" ] },
        { "strerror_l", [ "errnum", "locale" ] },
        { "strerror_r", [ "errnum", "buf", "buflen" ] },
        { "strerrordesc_np", [ "errnum" ] },
        { "strerrorname_np", [ "errnum" ] },
        { "strfmon", [ "s", "max", "format" ] },
        { "strfmon_l", [ "s", "max", "locale", "format" ] },
        { "strfromd", [ "str", "n", "format", "fp" ] },
        { "strfromf", [ "str", "n", "format", "fp" ] },
        { "strfroml", [ "str", "n", "format", "fp" ] },
        { "strfry", [ "string" ] },
        { "strftime", [ "s", "max", "format", "tm" ] },
        { "strftime_l", [ "s", "max", "format", "tm", "locale" ] },
        { "strlen", [ "s" ] },
        { "strncasecmp", [ "s1", "s2", "n" ] },
        { "strncat", [ "dest", "n", "const", "restrict", "size_t" ] },
        { "strncmp", [ "s1", "s2", "n" ] },
        { "strncpy", [ "dst", "src", "sz" ] },
        { "strndup", [ "s", "n" ] },
        { "strndupa", [ "s", "n" ] },
        { "strnlen", [ "s", "maxlen" ] },
        { "strpbrk", [ "s", "accept" ] },
        { "strptime", [ "s", "format", "tm" ] },
        { "strrchr", [ "s", "c" ] },
        { "strsep", [ "stringp", "delim" ] },
        { "strsignal", [ "sig" ] },
        { "strspn", [ "s", "accept" ] },
        { "strstr", [ "haystack", "needle" ] },
        { "strtod", [ "nptr", "endptr" ] },
        { "strtof", [ "nptr", "endptr" ] },
        { "strtoimax", [ "nptr", "endptr", "base" ] },
        { "strtok", [ "s", "delim" ] },
        { "strtok_r", [ "str", "delim", "saveptr" ] },
        { "strtol", [ "nptr", "endptr", "base" ] },
        { "strtold", [ "nptr", "endptr" ] },
        { "strtoll", [ "nptr", "endptr", "base" ] },
        { "strtoul", [ "nptr", "endptr", "base" ] },
        { "strtoull", [ "nptr", "endptr", "base" ] },
        { "strtoumax", [ "nptr", "endptr", "base" ] },
        { "strverscmp", [ "s1", "s2" ] },
        { "strxfrm", [ "dest", "src", "n" ] },
        { "swab", [ "from", "to", "n" ] },
        { "swapcontext", [ "oucp", "ucp" ] },
        { "swapoff", [ "path" ] },
        { "swapon", [ "path", "swapflags" ] },
        { "swprintf", [ "wcs", "maxlen", "format" ] },
        { "symlink", [ "target", "linkpath" ] },
        { "symlinkat", [ "target", "newdirfd", "linkpath" ] },
        { "sync_file_range", [ "fd", "offset", "nbytes", "flags" ] },
        { "syncfs", [ "fd" ] },
        { "sysconf", [ "name" ] },
        { "sysfs", [ "option", "fsname" ] },
        { "sysinfo", [ "info" ] },
        { "syslog", ["priority", "format" ]},
        { "system", [ "command" ] },
        { "sysv_signal", [ "signum", "handler" ] },
        { "tan", [ "x" ] },
        { "tanf", [ "x" ] },
        { "tanh", [ "x" ] },
        { "tanhf", [ "x" ] },
        { "tanhl", [ "x" ] },
        { "tanl", [ "x" ] },
        { "tcdrain", [ "fd" ] },
        { "tcflow", [ "fd", "action" ] },
        { "tcflush", [ "fd", "queue_selector" ] },
        { "tcgetattr", [ "fd", "termios_p" ] },
        { "tcgetpgrp", [ "fd" ] },
        { "tcgetsid", [ "fd" ] },
        { "tcsendbreak", [ "fd", "duration" ] },
        { "tcsetattr", [ "fd", "optional_actions", "termios_p" ] },
        { "tcsetpgrp", [ "fd", "pgrp" ] },
        { "tdelete", [ "key", "rootp", "compar" ] },
        { "tdestroy", [ "root", "free_node", "nodep" ] },
        { "tee", [ "fd_in", "fd_out", "len", "flags" ] },
        { "telldir", [ "dirp" ] },
        { "tempnam", [ "dir", "pfx" ] },
        { "tfind", [ "key", "rootp", "compar" ] },
        { "tgamma", [ "x" ] },
        { "tgammaf", [ "x" ] },
        { "tgammal", [ "x" ] },
        { "tgkill", [ "tgid", "tid", "sig" ] },
        { "time", [ "tloc" ] },
        { "timegm", [ "tm" ] },
        { "timelocal", [ "tm" ] },
        { "timer_create", [ "clockid", "sevp", "timerid" ] },
        { "timer_delete", [ "timerid" ] },
        { "timer_getoverrun", [ "timerid" ] },
        { "timer_gettime", [ "timerid", "curr_value" ] },
        { "timer_settime", [ "timerid", "flags", "new_value", "old_value" ] },
        { "timeradd", [ "a", "b", "res" ] },
        { "timerclear", [ "tvp" ] },
        { "timercmp", [ "a", "b", "CMP" ] },
        { "timerfd_create", [ "clockid", "flags" ] },
        { "timerfd_gettime", [ "fd", "curr_value" ] },
        { "timerfd_settime", [ "fd", "flags", "new_value", "old_value" ] },
        { "timerisset", [ "tvp" ] },
        { "timersub", [ "a", "b", "res" ] },
        { "times", [ "buf" ] },
        { "tmpnam", [ "s" ] },
        { "tmpnam_r", [ "s" ] },
        { "toascii", [ "c" ] },
        { "tolower", [ "c" ] },
        { "tolower_l", [ "c", "locale" ] },
        { "toupper", [ "c" ] },
        { "toupper_l", [ "c", "locale" ] },
        { "towctrans", [ "wc", "desc" ] },
        { "towlower", [ "wc" ] },
        { "towlower_l", [ "wc", "locale" ] },
        { "towupper", [ "wc" ] },
        { "towupper_l", [ "wc", "locale" ] },
        { "trunc", [ "x" ] },
        { "truncate", [ "path", "length" ] },
        { "truncf", [ "x" ] },
        { "truncl", [ "x" ] },
        { "tsearch", [ "key", "rootp", "compar" ] },
        { "ttyname", [ "fd" ] },
        { "ttyname_r", [ "fd", "buf", "buflen" ] },
        { "twalk", [ "root", "action", "nodep", "which", "depth" ] },
        { "twalk_r", [ "root", "action", "nodep", "which", "closure", "closure" ] },
        { "ualarm", [ "usecs", "interval" ] },
        { "ulimit", [ "cmd", "newlimit" ] },
        { "umask", [ "mask" ] },
        { "umount", [ "target" ] },
        { "umount2", [ "target", "flags" ] },
        { "uname", [ "buf" ] },
        { "ungetc", [ "c", "stream" ] },
        { "ungetwc", [ "wc", "stream" ] },
        { "unlink", [ "pathname" ] },
        { "unlinkat", [ "dirfd", "pathname", "flags" ] },
        { "unlockpt", [ "fd" ] },
        { "unsetenv", [ "name" ] },
        { "unshare", [ "flags" ] },
        { "updwtmp", [ "wtmp_file", "ut" ] },
        { "uselib", [ "library" ] },
        { "uselocale", [ "newloc" ] },
        { "usleep", [ "usec" ] },
        { "ustat", [ "dev", "ubuf" ] },
        { "utime", [ "filename", "times" ] },
        { "utimensat", [ "dirfd", "pathname", "times" ] },
        { "utimes", [ "filename", "times" ] },
        { "utmpname", [ "file" ] },
        { "va_copy", [ "dest", "src" ] },
        { "va_end", [ "ap" ] },
        { "va_start", [ "ap", "last" ] },
        { "valloc", [ "size" ] },
        { "vasprintf", [ "strp", "fmt", "ap" ] },
        { "vdprintf", [ "fd", "format", "ap" ] },
        { "verr", [ "eval", "fmt", "args" ] },
        { "verrx", [ "eval", "fmt", "args" ] },
        { "versionsort", [ "a", "b" ] },
        { "vfprintf", [ "stream", "format", "ap" ] },
        { "vfscanf", [ "stream", "format", "ap" ] },
        { "vfwprintf", [ "stream", "format", "args" ] },
        { "vm86", [ "fn", "v86" ] },
        { "vm86old", [ "info" ] },
        { "vmsplice", [ "fd", "iov", "nr_segs", "flags" ] },
        { "vprintf", [ "format", "ap" ] },
        { "vscanf", [ "format", "ap" ] },
        { "vsnprintf", [ "str", "size", "format", "ap" ] },
        { "vsprintf", [ "str", "format", "ap" ] },
        { "vsscanf", [ "str", "format", "ap" ] },
        { "vswprintf", [ "wcs", "maxlen", "format", "args" ] },
        { "vsyslog", [ "priority", "format", "ap" ] },
        { "vwarn", [ "fmt", "args" ] },
        { "vwarnx", [ "fmt", "args" ] },
        { "vwprintf", [ "format", "args" ] },
        { "wait", [ "wstatus" ] },
        { "wait3", [ "wstatus", "options", "rusage" ] },
        { "wait4", [ "pid", "wstatus", "options", "rusage" ] },
        { "waitid", [ "idtype", "id", "infop", "options" ] },
        { "waitpid", [ "pid", "wstatus", "options" ] },
        { "warn", [ "fmt" ] },
        { "warnx", [ "fmt" ] },
        { "wcpcpy", [ "dest", "src" ] },
        { "wcpncpy", [ "dest", "src", "n" ] },
        { "wcrtomb", [ "s", "wc", "ps" ] },
        { "wcscasecmp", [ "s1", "s2" ] },
        { "wcscat", [ "dest", "src" ] },
        { "wcschr", [ "wcs", "wc" ] },
        { "wcscmp", [ "s1", "s2" ] },
        { "wcscpy", [ "dest", "src" ] },
        { "wcscspn", [ "wcs", "reject" ] },
        { "wcsdup", [ "s" ] },
        { "wcslen", [ "s" ] },
        { "wcsncasecmp", [ "s1", "s2", "n" ] },
        { "wcsncat", [ "dest", "src", "n" ] },
        { "wcsncmp", [ "s1", "s2", "n" ] },
        { "wcsncpy", [ "dest", "src", "n" ] },
        { "wcsnlen", [ "s", "maxlen" ] },
        { "wcsnrtombs", [ "dest", "src", "nwc", "len", "ps" ] },
        { "wcspbrk", [ "wcs", "accept" ] },
        { "wcsrchr", [ "wcs", "wc" ] },
        { "wcsrtombs", [ "dest", "src", "len", "ps" ] },
        { "wcsspn", [ "wcs", "accept" ] },
        { "wcsstr", [ "haystack", "needle" ] },
        { "wcstoimax", [ "nptr", "endptr", "base" ] },
        { "wcstok", [ "wcs", "delim", "ptr" ] },
        { "wcstombs", [ "dest", "src", "n" ] },
        { "wcstoumax", [ "nptr", "endptr", "base" ] },
        { "wcswidth", [ "s", "n" ] },
        { "wctob", [ "c" ] },
        { "wctomb", [ "s", "wc" ] },
        { "wctrans", [ "name" ] },
        { "wctype", [ "name" ] },
        { "wcwidth", [ "c" ] },
        { "wmemchr", [ "s", "c", "n" ] },
        { "wmemcmp", [ "s1", "s2", "n" ] },
        { "wmemcpy", [ "dest", "src", "n" ] },
        { "wmemmove", [ "dest", "src", "n" ] },
        { "wmempcpy", [ "dest", "src", "n" ] },
        { "wmemset", [ "wcs", "wc", "n" ] },
        { "wordexp", [ "s", "p", "flags" ] },
        { "wordfree", [ "p" ] },
        { "wprintf", [ "format" ] },
        { "write", [ "fd", "buf", "count" ] },
        { "writev", [ "fd", "iov", "iovcnt" ] },
        { "xdecrypt", [ "secret", "passwd" ] },
        { "xencrypt", [ "secret", "passwd" ] },
        { "y0", [ "x" ] },
        { "y0f", [ "x" ] },
        { "y0l", [ "x" ] },
        { "y1", [ "x" ] },
        { "y1f", [ "x" ] },
        { "y1l", [ "x" ] },
        { "yn", [ "n", "x" ] },
        { "ynf", [ "n", "x" ] },
        { "ynl", [ "n", "x" ] },
    };
}
