// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
using XenoAtom.Interop.CodeGen.common;
using XenoAtom.Interop.CodeGen.libgit2;
using XenoAtom.Interop.CodeGen.musl;
using XenoAtom.Interop.CodeGen.sqlite;
using XenoAtom.Interop.CodeGen.zlib;

namespace XenoAtom.Interop.CodeGen;

partial class Program
{
    /// <summary>
    /// Gets the list of library descriptors generated by the code generator.
    /// </summary>
    private static readonly LibDescriptor[] LibDescriptors =
    [
        new()
        {
            Name = "common",
            Description = "Shared library providing `FixedArray#<T>` types for use in interop scenarios.",
            Url = "https://github.com/XenoAtom/Interop",
            Generator = desc => new EmptyGenerator(desc),
            HasGeneratedFolder = false,
        },
        new()
        {
            Name = "musl",
            Description = "musl is an implementation of the C standard library built on top of the Linux system call API.",
            Url = "https://musl.libc.org/",
            Generator = desc => new MuslGenerator(desc)
        },
        new()
        {
            Name = "libgit2",
            Description = "libgit2 is a pure C implementation of the Git core methods.",
            Url = "https://libgit2.org/",
            NativeNuGets = [new("LibGit2Sharp.NativeBinaries", "2.0.322")],
            Generator = desc => new LibGit2Generator(desc)
        },
        new()
        {
            Name = "sqlite",
            Description = "SQLite is a small and fast SQL database engine.",
            Url = "https://www.sqlite.org/",
            NativeNuGets = [new("SQLitePCLRaw.lib.e_sqlite3", "2.1.8")],
            Generator = desc => new SqliteGenerator(desc)
        },
        new()
        {
            Name = "zlib",
            Description = "Zlib library",
            Url = "https://zlib.net/",
            NativeNuGets =
            [
                new("elskom.zlib.redist.win", "1.2.13"),
                new("elskom.zlib.redist.linux", "1.2.13"),
                new("elskom.zlib.redist.osx", "1.2.13")
            ],
            Generator = desc => new ZlibGenerator(desc)
        },
    ];
}