# configuration file for dotnet-releaser
[msbuild]
project = "XenoAtom.Interop.common.sln"
[changelog]
publish = false # Disable changelog for now
[github]
user = "XenoAtom"
repo = "XenoAtom.Interop"
version_prefix = "common/"