name: ci_build_vulkan

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**' 
    paths:
    - 'src/*.props'
    - 'src/vulkan/**'
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mesa-vulkan-drivers \
            libvulkan1 \
            vulkan-tools
      - name: "Build, Test and Pack Vulkan"
        uses: xoofx/.github/.github/action/dotnet-releaser-action@main   
        with:
          dotnet-releaser-path: 'src/vulkan/dotnet-releaser.toml'
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
