name: ci_build_codegen

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**' 
    paths:
    - 'src/*'
    - 'src/codegen/**'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      dotnet-releaser-path: 'src/dotnet-releaser.toml'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
