name: ci_build_sqlite

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**' 
    paths:
    - 'src/*.props'
    - 'src/sqlite/**'
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      actions: write
      contents: write
    runs-on: 'ubuntu-latest'
    steps:
#GITHUB_ACTION_PRE_STEP
      - name: NuGet Login
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: xoofx
      - name: "Build, Test and Pack sqlite"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main   
        with:
          dotnet-releaser-path: 'src/sqlite/dotnet-releaser.toml'
          NUGET_TOKEN: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
#GITHUB_ACTION_POST_STEP
