name: ci_build_musl

on:
  push:
    paths:
    - 'src/*'
    - 'src/musl/**'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      dotnet-releaser-path: 'src/musl/dotnet-releaser.toml'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
