name: ci_publish_sqlite

on:
  push:
    tags:
      - "sqlite/*"
    paths:
    - 'src/*.props'
    - 'src/sqlite/**'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      dotnet-releaser-path: 'src/sqlite/dotnet-releaser.toml'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
