name: ci_publish_common

on:
  push:
    tags:
      - "common/*"
    paths:
    - 'src/*'
    - 'src/common/**'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      dotnet-releaser-path: 'src/common/dotnet-releaser.toml'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
