name: ci_publish_common

on:
  push:
    tags:
      - "common/*"
    paths:
    - 'src/*.props'
    - 'src/common/**'
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
#GITHUB_ACTION_PRE_STEP
      - name: "Build, Test and Publish common"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main   
        with:
          dotnet-releaser-path: 'src/common/dotnet-releaser.toml'
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
#GITHUB_ACTION_POST_STEP
