name: ci_publish_libgit2

on:
  push:
    tags:
      - "libgit2/*"
    paths:
    - 'src/*.props'
    - 'src/libgit2/**'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
      dotnet-releaser-path: 'src/libgit2/dotnet-releaser.toml'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
